### ISSUE TITLE
[QSRlib] Provide an easier way and some checking for uniqueness in the registration of the QSRs

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#108]
QSRlib should provide some checking that the QSR `unique_id` and the corresponding classes are unique.

**Comment by cdondrup** [comment]
This is a prime example for a unit test as well, addressing #34

**Comment by yianni** [comment]
PR #107 addresses the unittest also.

**Comment by cdondrup** [comment]
Closed via #107
