### ISSUE TITLE
Re-release before merging PR #107

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#120]
*Friendly Reminder*

Re-release before merging PR #107 which is non-backward.

Blocks PR #107.

**Comment by cdondrup** [comment]
Could do that now.

**Comment by yianni** [comment]
Whenever you feel like. 0.1.2 will be the last release before breaking backward compatibility. Can't think of anything else holding it back tbh so go ahead when you have a moment.

**Comment by cdondrup** [comment]
Re-release almost done, please keep in mind that this release also contains the qsr-prob-rep package (that should have been a reason to jump to 0.2 in the first place to be honest but never mind, didn't think about that) so you will need to run a dist-upgrade to update held back packages.

Also keep in mind that both packages in this repo will always have the same version number.

**Comment by yianni** [comment]
Indeed it probably should have been 0.2 for qsr-prob package, but oh well, nvm now.

TBH IMO I like that there are learning tools that use the QSR computation package within QSRlib, but I think that they all deserve a more generic package name, something like `qsr_lib_learning` and then have the `qsr_prob_rep` package under it.

We can chat about it on another specific issue and if you also agree that it would be a better file structure then include it as a milestone for 1.0.

**Comment by cdondrup** [comment]
Yes, we can chat about that at a v1.0 meeting, maybe at the GA.
