### ISSUE TITLE
Discuss, decide and organize which features should make it to the LAMoR QSRlib

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#121]
IMO 0.2 should be the base.

**Comment by cdondrup** [comment]
Sounds good to me. I'd say we just add what ever feature we need for the school to the 0.2 milestone.

**Comment by yianni** [comment]
It's the only way to do it as github does not allow assigning issues and PRs to multiple milestones unfortunately.

Leave the milestone of `LAMoR version` open though please as I send them an email about such a feature request and they already got back to me asking for an example (their customer support is awesome).

**Comment by yianni** [comment]
Closed by #139
