### ISSUE TITLE
[qsrlib_io] World_QSR_Trace.get_sorted_timestamps method does not look right

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#122]
`World_QSR_Trace.get_sorted_timestamps` method does not look right.

**Comment by cdondrup** [comment]
Something like:

```
def get_sorted_timestamps(self):
        return sorted(self.trace.keys(), key=lambda x: int(x))
```

maybe?

**Comment by yianni** [comment]
What if they are float timestamps?

Basically one more thing to deprecate and enforce to one standard that timestamps can be only numeric; leaving the get_sorted_timestamps as a wrap method to simply:

```python
def get_sorted_timestamps(self):
    return sorted(self.trace.keys())
```

**Comment by cdondrup** [comment]
Can also just do:

```python
def get_sorted_timestamps(self):
        return sorted(self.trace.keys(), key=lambda x: float(x))
```

which works for both ;)

But I agree, if the conversion is not necessary, get rid of it.
