### ISSUE TITLE
Communicate once more to STRANDS WP8

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#124]
Communicate to STRANDS WP8 that version 0.1.3 (or 0.1.3+ on a per need to fix bugs) will be the latest that supports the non-backward compatible changes in PR #107

**Comment by yianni** [comment]
Assign this to @cdondrup as I am away next week with limited to no access to email.

If you can please send an email before or on merging of #107 just letting people know that if they need backward compatibility they should check out 0.1.3 release version.

Thanks.

**Comment by cdondrup** [comment]
Done
