### ISSUE TITLE
Test effect of issue #11

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#14]
I see you already moved it. OK, I will test and see if there are any issues.

Test that
```python
self.client_node = rospy.init_node("qsr_lib_ros_client_example")  # needed for rospy.get_rostime() in the request method
```
that was moved from `qsrlib_ros_client.py` to `example_ros_client` doesn't  cause a problem with 
```python
req.header.stamp = rospy.get_rostime()
```
in `qsrlib_ros_client.py/QSRlib_ROS_Client/make_ros_request_message`

**Comment by yianni** [comment]
Can't change labels? Can't assign it to myself?

**Comment by cdondrup** [comment]
I made you an admin of this repo so now you should be able to do that.

As I said, tested it for qtc. Please test it for rcc. But it can't break anything. If it does we have to think of something else because it cannot stay the way it was.

**Comment by cdondrup** [comment]
I assume this didn't cause any problems as we all ran the lib and no one complained ;)
