### ISSUE TITLE
[QSRlib] Investigate the story with `custom_checks`

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#144]
Method only used in QTCS currently. Maybe there can be a workaround and deprecate if decided that it is not needed.

**Comment by yianni** [comment]
Given that QTCS is the only one currently using it probably best if you have a look whether you actually need it. It might also be related to #142 as when bypassed QTCS relations are returned with missing values (whether they are valid and correct is another story).

No rush for it though.

**Comment by cdondrup** [comment]
I mainly implemented them to try it ;) QTC actually does make a few checks in the make routine as well. 

I don't think the custom_checks are really necessary. If the dyadic abstract class ensures that there are two objects for each timestamp, then I'm fine with scrapping it.

**Comment by yianni** [comment]
TL'DR: No, the vanilla dyadic does not do that check (or more accurate the specific check required by QTCS). Must all objects requested QTC relations be present at all timestamps?

In more detail, the dyadic checks via `qsrs_for` if the pair is present at a given . But what you need is a 2t check, something like the `QSR_Monadic_1t_Abstractclass`.

But the key question is: "Is QTCS family able to cope with missing values?" E.x. you have 3 objects o1, o2, o3 and a world_trace of 5t; let's say that o1, o2 are present all the times but o3 is present at t=2 and 3 only. What QTCS is expected to do there? QTCBS with no_collapse=True, and validate=False will be safe and work fine in the above example. What if no_collapse=False and/or validate=True though?
