### ISSUE TITLE
set_from_config_file: does it even work still? should be deprecated?

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#149]
Only argd currently uses it and whether it still works in 0.2.0 remains to be tested. Should this remain where it is as it complicates things (unncecessariy IMO), or should be provided as a utilities function to a user, or deprecated completely?

**Comment by pet1330** [comment]
I think it should be an option, it shouldn't complicate it too much, even if it just checks the file when starting and passes it as dynamic args automatically thereafter?

**Comment by yianni** [comment]
Yes, that's where I am leaning towards to; being a functionality offered to the client and the yaml format of the config file should be such that it is read straight as `dynamic_args`.

**Comment by cdondrup** [comment]
Just leave it to the client, yes. Then you can just use the ros internal functions like roslaunch to read the yaml file and get it from the parameter server. Don't burden the lib with that.

**Comment by yianni** [comment]
OK, since there are no objections it will move to client side. Won't do any changes though before Sunday's LAMOR to keep the lib in its current version.

**Comment by cdondrup** [comment]
:+1:

**Comment by pet1330** [comment]
:+1:

**Comment by yianni** [comment]
And @yianni don't forget to remove the [corresponding field from the request message](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib/qsrlib.py#L25).

**Comment by yianni** [comment]
closed by #151
