### ISSUE TITLE
add type to QSR class

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#15]
@cdondrup I am thinking of adding a type field (string) to [`QSR` class](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_io/world_qsr_trace.py#L4) that will make life easier if a `QSR` object contains multiple relations within its `qsr` string field.

For example if you wanted to describe qualitative distance and speed between two objects you would have to have something like: `QSR.qsr = "far,fast"` or any other notation like `+,+`. This makes it difficult to remember what is what. The type could provide a hint and could also be used for parsers/decomposers if needed, e.g. in this example `QSR.type = "distance,speed"`.

This change should not break any existing code as I will have it as an optional argument with default value being an empty string.

**Comment by cdondrup** [comment]
Might be useful, but I don't immediately see the benefit over just putting it in a readme.
If it doesn't break stuff, no problem adding it. But you would have to return it in the service for it to be useful. Having a description inside the implementation does not help anybody using the library without looking at the code.

**Comment by yianni** [comment]
Agree. And I also remembered there is kwargs, but oh well I will leave it for now (should not break anything), and yes with lack of ROS on my work PC did not want to change the service without being able to test it.
