### ISSUE TITLE
[rostest] QTCS gives a warning in multiple_tester

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#159]
During the run of `multiple_tester` QTCS family give the following warning: 
```bash
$HOME/catkin_ws/src/strands_qsr_lib/qsr_lib/src/qsrlib_qsrs/qsr_qtc_simplified_abstractclass.py:310: RuntimeWarning: invalid value encountered in double_scalars
  )/np.linalg.norm(line[1,0:2]-line[0,0:2])
```

Preliminary debugging shows that It happens in `test_defaults` with datasets data1, data2 and data3 as well as with the other tests that use data1.

Might add a 2nd test for QTC at some point similar to the others.

Unable to assess how critical this is or whether it is an actual bug.

**Comment by yianni** [comment]
Confirmed it happens in solo run for qtcbs, qtccs, qtcbcs for data1, data2 and data3; strangely not for data4.

**Comment by yianni** [comment]
Further warning for QTBCS which happens with datasets:
```bash
~/catkin_ws/src/strands_qsr_lib/qsr_lib/src/qsrlib_qsrs/qsr_qtc_simplified_abstractclass.py:106: RuntimeWarning: invalid value encountered in greater
  insert[np.abs(qtc[i-1,:]-insert)>1] = 0
```

**Comment by cdondrup** [comment]
That might happen due to nan values. Is this important? This is kind of a feature imho.

**Comment by yianni** [comment]
Is it breaking the calculation of QTCS values when nan values are the case?  If not
![image](https://cloud.githubusercontent.com/assets/167472/9717444/b4da28a6-556a-11e5-9c89-d419e8bd6e3b.png)

**Comment by cdondrup** [comment]
No, that is the feature I meant; It ignores nan values because of that warning. So works as intended.
