### ISSUE TITLE
get_sorted_timestamps in World_Trace and World_QSR_Trace are not correct

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#16]
get_sorted_timestamps in [World_Trace](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_io/world_trace.py#L56) and [World_QSR_Trace](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_io/world_qsr_trace.py#L26) do not return the timestamps sorted correctly due to them being stupid strings for easier ROS serialization.

Will submit a dirty inefficient fix for now.

**Comment by cdondrup** [comment]
Why don they have to be strings? I use and return arrays in qtc. No problem what so ever. But maybe I just don't get the problem.

**Comment by yianni** [comment]
It's about the timestamps-keys of the dictionaries in both `World_Trace.trace` and `World_QSR_Trace.trace`. It only affects time-dependent QSRs (like QTC) depending on whether you are calling the `get_sorted_timestamps` and you parse via it; it has no effects on single time QSRs (like RCC3). The effect is easier to show with the following MWE:

```python
def bad_previous_sort(l):
    return sorted(timestamp_keys)

def good_new_sort(l):
    ret = l
    foo = ret[0]
    ret = [int(i) for i in ret]
    ret = sorted(ret)
    if type(foo) is str:  # if they were str make them strs again
        ret = [str(i) for i in ret]
    return ret

timestamp_keys = ["2", "1", "20", "5", "4", "22", "9", "6", "7", "8", "11", "10"]
print "bad_previous_sort:\t", bad_previous_sort(timestamp_keys)
print "good_new_sort:\t\t", good_new_sort(timestamp_keys)
```

```
bad_previous_sort:    ['1', '10', '11', '2', '20', '22', '4', '5', '6', '7', '8', '9']
good_new_sort:        ['1', '2', '4', '5', '6', '7', '8', '9', '10', '11', '20', '22']
```

Would not have been a problem if they were numerics instead of strings.
