### ISSUE TITLE
Where to host the docs?

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#169]
@marc-hanheide 

Where are we meant to host docs from the STRANDS projects? Options I see are:
* [github-pages](https://pages.github.com/), which requires a separate branch `gh-pages` according to their instructions.
* [Read the Docs](https://readthedocs.org/), can be linked to github repo and requires no additional branch AFAIK, but it does require an account. Can do it under mine if you want.
* Somewhere else?

**Comment by marc-hanheide** [comment]
not sure what sort of documentation you're talking about. Normally, we'd use the `README.md` for the briefer instructions, and then the Wiki when more pages are required.

**Comment by marc-hanheide** [comment]
Oh, or are you talking about autogenerated python docs?

**Comment by yianni** [comment]
Yes sphinx html docs.

**Comment by yianni** [comment]
[See here](http://qsrlib.readthedocs.org/) for the generated docs under my account

**Comment by marc-hanheide** [comment]
the way you did that looks alright to me... Just link it from `README.md`?

**Comment by yianni** [comment]
Yes would do that... was investigating what option you prefer in terms of where they should be hosted. If you are fine with API doc being in readthedocs under my account go ahead and close the issue.

**Comment by marc-hanheide** [comment]
I don't mind too much. There is the infrastructure to auto-generate those docs from STRANDS repos via the build farm, but I have not enabled it yet and didn't plan to do any time soon. So, for now at least, keep it there and link it.
