### ISSUE TITLE
Rename length, width, height to xsize, ysixe, zsize

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#173]
Opinions? Related to #105 .

**Comment by pet1330** [comment]
They seem sensible. Just to clarify, I still think it should be in relation to the ROS standards, as shown above :)

For Example:

| Label| ROS Standard | current  | Old suggestion |  new suggestion | 
| :-------------: |:-------------:| :-----:|:-----:|:-----:
| Width | Y | X | X | ySize |
| Length | X  |   Y | Z | xSize |
|Height | Z  |    Z | Y | zSize |

**Comment by yianni** [comment]
Cool.

Open a new issue for x,y,z and copy paste the table above, as this is a different issue.

**Comment by yianni** [comment]
@cdondrup  @PDuckworth what about you? Do you explicitly remember using anywhere `o.length`, `o.width` and `o.height`? Otherwise, the change will be unnoticed (used primarily in the bboxes calculation).

**Comment by cdondrup** [comment]
I don't. Go ahead.

**Comment by yianni** [comment]
closed by #177
