### ISSUE TITLE
Replace roll, pitch, yaw with quaternions just like in ROS

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#174]
Opinions?

**Comment by cdondrup** [comment]
Roll, pitch and yaw are a bit easier to understand, for me at least, and easy to generate from within ROS. So for the usage without ROS I don't think quaternions are necessarily better but for the usage with ROS it saves you one or two steps.

I don't have a real opinion on that to be honest as I don't use it much. How about both? :P
If a 3-tuple is given assume rpy and a 4-tuple is a quaternion?!

**Comment by yianni** [comment]
There is no doubt that roll, pitch yaw are easier to understand. The only issue with them is that it depends on which are the x,y z axes which relates to issue that @pet1330 has brought up. Quaternions on the other hand have an x,y,z (and a w) component which makes it much more distinct.

We could in theory provide a rpy2quaternion function but it will still suffer on what is our interpretation of x,y and z.

Both could be an option, requires changing the represention to list a bit as they are standonlone members now, and could be handled via setter, getter methods eventually. Hmmm, might do that for now and if proves to complex in the future it can be changed again :).

Although still does not clearly solve how rpy maps to xyz and would hate to create another length, width, height situation.

**Comment by pet1330** [comment]
> The only issue with them is that it depends on which are the x,y z axes

I think as long as its consistent, it shouldn't matter too much from the users perspective. It only really makes a difference from the developers point of view. I think @cdondrup's idea is good here:

> If a 3-tuple is given assume rpy and a 4-tuple is a quaternion

If a 4-tuple is given, then you've got all the information you need, if a 3-tuple is given, you'll have to just assumption like we do now.

**Comment by yianni** [comment]
It's already done with both :).

**Comment by yianni** [comment]
closed by #177
