### ISSUE TITLE
RCC3 is wrong

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#183]
Deprecate RCC3 which is wrong (both symbolically and conceptually) and replace it with an RCC4 which includes an inverse relation.

**Comment by yianni** [comment]
@pet1330 With respect to recent comment that you are using it, I will close this issue.

Might want to consider that there is an inverse missing relation in rcc3, if x occludes y, then what is the relation between yx?

**Comment by pet1330** [comment]
This is only relevant if you want to distinguish the inverse, which in my particular example, I don't.

**Comment by yianni** [comment]
I thought so as much, it was same for me in the past (see other comment). OK we can discuss and sort out RCC3 at a later stage, which requires deciding on two issues if it is to be kept:

* where do the inverse relations map to?
* we probably should use RCC8 or RCC5 vocabulary (as it is my vote to RCC8).
