### ISSUE TITLE
QSRLib Question

### ISSUE THREAD

**Issue by PDuckworth** [strands-project/strands_qsr_lib#20]
I have succesfully implemented qsrlib's qtcb for pairwise objects. I do this by creating an instance of World_Trace() for each pair of objects in the scene. This seems inificient. Can I create one World_Trace, and pass all the object_state_series at once? 

I think Yiannis said this was possible in rcc. Is it also possible in the qtc code? @cdondrup @yianni

**Comment by cdondrup** [comment]
I guess works something like in [here](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_rcc3_rectangle_bounding_boxes_2d.py#L52-L59) if so, I would have to add that. Will do when I have time since this is a feature I will need as well. I'll let you know but I don't know when I have time for that. Maybe in the beginning of next week.

**Comment by PDuckworth** [comment]
Having discussed this with Yiannis, it's actually clear that returning all combinations of objects passed to World_Trace() is not such a smart idea for qtc. 

i.e. If I pass a trajectory id, and 3 objects, I require the qtc relations for trajectory-object pairs. Not all combintations of the 4 (total) object_states passed. Would this make your implementation too specific? 

Further, my code currently runs fine, so there is no rush to alter the qtc!

**Comment by yianni** [comment]
@cdondrup @PDuckworth 
Yes, it would be nice to pass a `World_Trace` of arbitrary number of t-steps (`World_State`) consisting of arbitary number of objects (`Object_State`) at each t, as this is the general direction of the QSRlib and it shouldn't really break any existing code as you could still pass a `World_Trace` of two `World_State` of two `Object_State`.

About creating qsrs for specific combinations, I agree it would be nice but not an absolute necessity at a first stage as it could be handled on the caller side, it just makes it more inefficient as they will be created and then parsed and poped.

This could be achieved by passing some form of filter but it might require either use of kwargs or need to add a type field on [`Object_State`](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_io/world_trace.py#L15), which will require modification of the ROS server client also.

Anyway, I will create a ticket (enhancement) about the first one for now and assigned to @cdondrup for when you have time to fix it, and we can further discuss about the filtering at some point.

**Comment by PDuckworth** [comment]
Yep, it turns out my needs are not in the true philosophy of qsrlib so my code will remain unaltered by any changes you make. 

Since I only require trajectory-object pairs returned, I will continue to initialise World_Trace() with just two object_states at a time.

**Comment by yianni** [comment]
Yes, that would probably be better since it seems specific.

**Comment by cdondrup** [comment]
@PDuckworth this is exactly what I need as well, robot->human[] qtc relations. But Having the general option getting all possible combinations is more general. I'm not sure yet of this specific implementation should go into the lib or be handled on the client side.

**Comment by PDuckworth** [comment]
@cdondrup It seems easy enough to create multiple World_Trace()'s, one per pair. This is what I plan on doing /continuing to do.

In fact, Yiannis and I discussed having one World_Trace() per trajectory, with object_state information per timepoint. Then adding a single object's object_states to this World_Trace before calling the qsr_server. This would be quite efficient I think. Slightly more complicated though.
