### ISSUE TITLE
QTCb returning too many timepoints

### ISSUE THREAD

**Issue by PDuckworth** [strands-project/strands_qsr_lib#27]
@cdondrup out.qsr.trace has more timepoints than world.trace input. 

I pass 44 poses (UUID, obj pairs), and it returns 47 traces. 

See screenshot for example (highlighted in terminal). 

![screenshot from 2015-03-25 10 52 42](https://cloud.githubusercontent.com/assets/5286841/6823186/cdc4f6c6-d2dd-11e4-92eb-17d4ac464fbf.png)

FYI, RCC3 returns 44 timepoint (for comparison).

**Comment by cdondrup** [comment]
QTC is not able to represent time quantitatively. It collapses similar adjacent states and inserts new states to create a valid state chain turning illegal transitions into several legal ones. If you have a look at the example ros client, there you can run it with `--validate` which inserts new states to turn illegal transitions into a series of legal ones. So if you run it without that option and with `no_collapse` set to true, then you should get 44. But, as I said this is not a valid state chain as it contains duplicates in adjacent states and invalid transitions.

If you could tell me how you run it and send me some example data, I might be able to have a look.

**Comment by PDuckworth** [comment]
@cdondrup OK, thanks for the propmt response.

I understand the `--valitate` parameter (I think). But I have it set to False. So I only expect the actual relations, even if they are ilegal wrt the conceptual neighbourhood graph.

I have `--no_colapse` set to True, but I am not certain what that parameter does (sorry).

**Comment by PDuckworth** [comment]
PS I run with `--validate` as false, and `--no_colapse` as True, and it still returns 47 timepoints. :(

**Comment by cdondrup** [comment]
@PDuckworth that does sound very weird. In fact if you have 44 point sets for two agents you should get 42 qtcb relations since this only works on two point sets at a time, meaning: t_0 -> t_1, t_1 -> t_2, ... 

If you have a file where this is stored you can test that with the example ros client. The file has too look like this: https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/share/qtc_data/qtc_real_world_example.csv and the you can run it with:
```
rosrun qsr_lib example_ros_client.py qtcb --no_collapse -i my_data_file.csv
```

That should the print the 42 relations in qtcb. Also with `rosrun qsr_lib example_ros_client.py --help` you hopefully get a helpful output on how to use it and can experiment with the different features.

Regarding the collapsing of states, if you have a state chain that looks like this:
```
0-,--,--,--,--,--,00
```
this would be turned into:
```
0-,--,00
```
because similar adjacent states are collapsed into one state. So you have to run it with no_collapse set to true to get this state chain using qtc symbols but which is not really a qtc state chain.

**Comment by cdondrup** [comment]
If this still does not work, maybe you can send me the file you're using and I have a look.

**Comment by PDuckworth** [comment]
"... you should get 42 qtcb relations since this only works on two point sets at a time,"

Surely it should return 43?  t1-t2, t2-t3,... , t43-t44 ?? There should be 43 transitions.

**Comment by cdondrup** [comment]
Mh... you're right... Let me have a look

**Comment by PDuckworth** [comment]
Altho, that is currently not the real problem. Thanks for clarifying though.

**Comment by cdondrup** [comment]
OK, Just me being stupid. The `wc` on the input file of course counts the header as well. So you should get 43 for 44 inputs, yes. Just couldn't handle my maths ;)

**Comment by cdondrup** [comment]
Tested it again on my PC using the example client... using various amounts of data, and it always returns the correct amount of relations. Also, this part: https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_qtc_simplified_abstractclass.py#L372-L387 creates the qtc representation and cannot run for more than n-1 times, n being the amount of timesteps.

Can you point me to the code where you call the library?

**Comment by cdondrup** [comment]
This is how I do it, starting from the convert function: https://github.com/cdondrup/strands_hri/blob/hrsi/hrsi_representation/src/hrsi_representation/input_base_abstractclass.py

**Comment by PDuckworth** [comment]
I only pass 4 worlds, each with two objects (traj-obj pair), and each has 44 poses. 

My code is here: https://github.com/PDuckworth/strands_data_to_qsrlib/blob/master/src/novelTrajectories/traj_data_reader.py

specifically the `apply_qsr_lib` and `get_qsrlib_world`.

**Comment by cdondrup** [comment]
Can I test that somehow? How would I run that with what data?

**Comment by PDuckworth** [comment]
I will try to output my data... but see attached screenshot for my baffling progress...

![screenshot from 2015-03-25 18 06 45](https://cloud.githubusercontent.com/assets/5286841/6831688/d33880c8-d319-11e4-9baf-1880aab5506d.png)

You can see printed at the top (left terminal) the World.trace I pass to the qsrlib_response. It starts off the screen, but it has 44 key-value pairs (last one is "43" since it starts at 0.) I then print just the keys, (of which there are 44), then I print the relations in `out.qsrs.trace[t].qsrs` key-value pairs (as per the example). And there are 47 of them. 

This is ran using `--validate` = False, and `--no_colapse` = True

**Comment by PDuckworth** [comment]
PS "also this part: ... creates the qtc representation and cannot run for more than n-1 time"

Is correct. It has 44 timepoints... I'll keep digging...

**Comment by PDuckworth** [comment]
I print timestamps [here](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_qtc_simplified_abstractclass.py#L362) and it is correct (44).

But by the time I get to ret [here](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/src/qsrlib_qsrs/qsr_qtc_simplified_abstractclass.py#L404) `len(ret.trace)` is length 47 :(

**Comment by cdondrup** [comment]
Can you check the length after line 392 and 394?

**Comment by cdondrup** [comment]
It looks like it is validating your state chain. Because there are 4 state changes that look like they have been inserted to make it valid which is also the number of extra states. That makes me a bit suspicious.

**Comment by PDuckworth** [comment]
Something strange is happening. 

`input_data.trace[0].objects[o1_name].kwargs["validate"]` is False, but the if statement is being executed.

**Comment by PDuckworth** [comment]
My `--validate` and `--no_collapse` are strings!!!

**Comment by cdondrup** [comment]
Are you sure it is `False` or might it be `"False"`
If it is a string instead of a bool then the if would be executed. `input_data.trace[0].objects[o1_name].kwargs["validate"]` has to be a bool, `None`, or `0` otherwise it is true.

Your config parser never sets any data type. I suspect that these are all strings and that `no_collapse` works because it is not `False`, `None`, or `0` but a string as well. Please type them explictly and then everything should work.

**Comment by cdondrup** [comment]
I can only recommend using `argparse`, like in [the example ros client](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/example_ros_client.py#L28-L41)

**Comment by PDuckworth** [comment]
We came to the same conclusion. :'(

**Comment by cdondrup** [comment]
I assume that fixes the problem. Please re-open if it doesn't or open a new one if you discover more ;)

I'll open a dedicated issue to implement a custom check if the values are bool or not to prevent this from happening in the future. Thanks for beta testing this :D
