### ISSUE TITLE
[QSRlib] Add rostests

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_qsr_lib#34]

**Comment by cdondrup** [comment]
Done for QTC: see #68 

For the others, @yianni, @PDuckworth, and @pet1330 have to write some.

**Comment by yianni** [comment]
Do they have to be *ros* tests? Pure python unittests won't work? Noticed that [this unittest](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/tests/utest_qsrlib_unique_developed_qsrs.py) was not triggered in a PR. :(

**Comment by cdondrup** [comment]
Short answer, yes.
Jenkins only builds rostest because they are triggered via catkin.

**Comment by yianni** [comment]
OK :(

**Comment by hawesie** [comment]
But you can implement them as Python unittests still.

**Comment by cdondrup** [comment]
It's not complicated, just have a look at:
https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/tests/qtc_tester.test
https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/tests/qtc_tester.py
and 
https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/CMakeLists.txt#L39-L42

**Comment by yianni** [comment]
> But you can implement them as Python unittests still.

and just wrap them in ROS I take it? If yes that's what I was planning to do.

**Comment by yianni** [comment]
> It's not complicated, just have a look at:

Thanks. Yes had seen them just thought that pure python would work too. Will wrap it at some point.

**Comment by yianni** [comment]
Assigning it to me as I already had something that did not want to push to the 0.2 PR. To avoid duplicate efforts.

**Comment by yianni** [comment]
closed by #152 (mostly)
