### ISSUE TITLE
[rcc3] dc and po at the same time?

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_qsr_lib#40]
We (@pet1330 and I) just had a look at the rcc3 output of the example client:

```
Response is:
0: o2,o1:dc; o2,o3:dc; o1,o3:dc; o1,o2:dc; o3,o2:dc; o3,o1:po; 
1: o2,o1:dc; o2,o3:dc; o1,o3:dc; o1,o2:dc; o3,o2:dc; o3,o1:po; 
2: o2,o1:dc; o2,o3:dc; o1,o3:po; o1,o2:dc; o3,o2:dc; o3,o1:po;
```

How can o1,o3 be disconnected and o3,o1 be partially overlapping at the same time? Also the objects shouldn't overlap looking at the coordinates and bounding boxes. Something might be wrong with the logic here.

**Comment by yianni** [comment]
Hmm, valid question. I will check it out when I find a chance.
