### ISSUE TITLE
[QTC] Make compliant with --future from #49

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#50]
As --future returns QSR dictionaries, the only QSR not complying is QTC as there were some things not clear to me when I try to edit it.

Either @yianni to have another look or @cdondrup

Not high priority at the moment.

**Comment by cdondrup** [comment]
I can do that.

**Comment by yianni** [comment]
@cdondrup Just to ask how are you thinking of doing it? My feeling would be something as follows: qtcb `{"qtcb": <relation>}`, qtcc `{"qtcc": <relation>}` and qtcbc `{"qtcb": <relation>, "qtcc": <relation>}`.

How does this sound? Let me know when you think about it.

**Comment by cdondrup** [comment]
This is not really the purpose of qtcbc. If I wanted that I could just get qtcb and qtcc. Deciding when to transition is quite important here. So it will be `{"qtcbc": <relation>}`.

**Comment by yianni** [comment]
Hmmm. Are these QTCs here different that what is described in section 3 of a later paper from Van de Weghe 2004, which provides a concise and clear description of QTC2d [link](http://arxiv.org/pdf/1402.3779.pdf).

**Comment by cdondrup** [comment]
qtcbc is because that was our invention. For qtcb and qtcc I currently only use two points in time instead of three which is a more simplified version of it.

**Comment by cdondrup** [comment]
This is what I am doing: http://www.mdpi.com/2218-6581/4/1/63

**Comment by yianni** [comment]
> This is what I am doing: http://www.mdpi.com/2218-6581/4/1/63

OK, I will have a look. Just the name implies that qtcbc = join(b, c). Anyway, do as you see fit.

**Comment by cdondrup** [comment]
Which is what it does ;) But with a bit of logic behind it.
