### ISSUE TITLE
[QTC] move custom arguments from object creation to service call

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_qsr_lib#53]
Currently the `quantisation_factor`, `validate`, `no_collapse`, and `distance_threshold` are added to each object. This is unnecessary and could go into the service calls using the `ini` argument if this would support strings or as separate arguments.

**Comment by yianni** [comment]
Sure, just bear in mind that this would work if they remain constant for all objects and for all timesteps. If that's the case it could be done.

The ini argument is just a filename, so they can be read from a file. If you don't want them to be read every time a call is made (agree bad idea), then the `dynamic_args` should be used... Haven't used it and tested it, but I added it cause I could foresee that passing a file to read from at every call is a bad idea... My thought was that `dynamic_args` should be used in the qsr as kwargs["dynamic_args"][<parameter>]

**Comment by yianni** [comment]
You can also change them at runtime per request (or use the last ones set if nothing passed). See for example #54

**Comment by yianni** [comment]
And while at it, would it be possible please to change the default to be no-collapse. I think it is confusing to get different number of outputs for inputs. I think validate is by default false. If not the same applies to it.

**Comment by cdondrup** [comment]
Even though it might confusing, I can't highlight enough that that would result in invalid qtc representations. IMHO, if you know qtc, using no_collapse and not validating it would be more confusing and if you don't know qtc, you won't be using it. I'm sorry I have to be that frank but I don't want to make that the default.
