### ISSUE TITLE
Change config file to use yaml format

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_qsr_lib#55]
This is normally used in ROS and also easily loadable.
Just a suggestion.

**Comment by yianni** [comment]
Yes possibly. Certainly more powerful and flexible but it also depends on how easy it to write, which seems a bit more complex than an ini file [yaml example](http://www.yaml.org/start.html). Neverthless, probably I will change it to yaml when I get some time.

**Comment by cdondrup** [comment]
For the current config file it would be:

```
arg_relations_distance:
  relations_and_values:
    "0": 5.
    "1": 15.
    "2": 120.
```

which would create this dict:
```
{arg_relations_distance: {relations_and_values: {"0": 5., "1": 15., "2": 120.}}}
```

Like python this is indentation sensitive but I find it quite easy to read and write.

**Comment by yianni** [comment]
Yes I know, that was my thoughts also and I already had a look before hand but wanted something quickly. It is possible with ini files, but not using configparser, but rather something like [configobj](http://www.voidspace.org.uk/python/configobj.html). Unfortunately, it seems that it does not come by default installed in a standard python environment, and hence I did not want such a dependency. So was stuck with configparser and eval(variable).

Hence, I am considering the yaml format. Wonder if pyyaml comes with standard python installation or it is simply installed as a dependency of ros.

PS: yes installing python packages is easy :)

**Comment by yianni** [comment]
Of course the alternative would be to use [configobj](http://www.voidspace.org.uk/python/configobj.html). See also [example here](http://www.voidspace.org.uk/python/configobj.html#reading-a-config-file).

All depends which one is easier to write (probably the same), or to parse.
