### ISSUE TITLE
Setting default values of objects to NaN instead of 0

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_qsr_lib#6]
Would it be possible to set the default values for, e.g. x and y, to NaN or Inf instead of 0? That way it would be possible to see if the values have been entered properly. In the QTC case it could very well be that x and y are 0 but someone could also have forgotten to give them values. In order to wrie an exhaustive custom check this would have to be changed.

**Comment by yianni** [comment]
Will investigate and get back to you. Don't see a problem of not being 
able to do so at first thought.

Christian Dondrup wrote:
