### ISSUE TITLE
trigger new public release

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#66]
@marc-hanheide I am quite happy with the current state of the QSRlib, so if @cdondrup also agrees I would like to trigger a new release as there are significant differences and enhancements from the latest ones.

Also (probably my fault as it has my signature) for some reason if you look in the [releases page](https://github.com/strands-project/strands_qsr_lib/releases) it gives as "latest release" a fairly old one. Not sure how this happened (I tagged it maybe?), why or how to change it.

Whenever @marc-hanheide you (or any of the jenkins admins) have time if you could please look into these two things.

Thanks.

**Comment by marc-hanheide** [comment]
Goto http://strands-project.github.io/rosdistro/ enter `strands_qsr_lib` and hit release.

**Comment by marc-hanheide** [comment]
This will tag a new release and trigger the build farm to build packages after I or someone else with the right permission has approved the release.
