### ISSUE TITLE
[QSRs] Simultaneous computation of multiple QSRs does not allow for individual `dynamic_args`

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#90]
The new feature of computing multiple QSRs with one service call does not allow to pass individual parameters. E.g. `quantisation_factor` for `qtcbs` and `mos` are forced to use the same. These keys need to be uniquely renamed. In fact, all parameters belonging to a QSR should have a namespace. Easiest way to do this is to prefix with their short unique name.

**Comment by cdondrup** [comment]
Regarding the actual name space, so we both implement the same, should it be:

```
{"qtc": {"quantisation_factor": 0.01, ...}}
```

or just 

```
"qtc_quantisation_factor"
```

I do like the first one better as it appears more pythonic to me and prevents me from prefixing 5 parameters for every qtc variant.

**Comment by yianni** [comment]
+1 on first also without doubt, more "effort" but more dynamic. String prefix less effort but less dynamic.

**Comment by cdondrup** [comment]
While altering all this, I think it would make sense to also change the names of the QSRs in the example client to the new short versions, i.e. `qtcb` to `qtcbs`. I can quickly do that while implementing the namespaces because then I can just take that string as the namespace as well.

**Comment by yianni** [comment]
+1
