### ISSUE TITLE
[QTCS] QTCS namespace of dynamic args

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#92]
Make `dynamic_args` of QTCS to have a namespace. Easiest resolve, to prefix them with `qtcs_`, `qtcbs_`, etc as needed.

**Comment by cdondrup** [comment]
I didn't think of that. Well spotted. Will fix.

**Comment by yianni** [comment]
Thanks. Will do the same for MOS as soon as I can.

**Comment by cdondrup** [comment]
Once I fix it for qtc I can fix it for mos as well if you like.

**Comment by yianni** [comment]
As you wish. Can you have the dict key as `qtcs` though?

**Comment by yianni** [comment]
Or `qtcbs`, `qtcs`, `qtcbcs` if they are specific.

**Comment by cdondrup** [comment]
Of course.

**Comment by yianni** [comment]
Great thanks.
