### ISSUE TITLE
[QSRLib] Remove empty print from ros server

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_qsr_lib#96]
[This](https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_lib/scripts/qsrlib_ros_server.py#L39) has annoyed me ever since and I don't see its use really. Can we please remove this?

**Comment by yianni** [comment]
[I like to stare at it.](http://www.imdb.com/title/tt1234548/)

**Comment by yianni** [comment]
closed by #99

**Comment by cdondrup** [comment]
Thank you :)
