### ISSUE TITLE
[QTCS] Always prints deprecation warning even if correct structure of dynamic args is used

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#98]
Always prints deprecation warning even if correct structure of dynamic args is used (introduced in #94)

**Comment by yianni** [comment]
[I like to stare at it.](http://www.imdb.com/title/tt1234548/)

**Comment by yianni** [comment]
I can fix that @cdondrup

**Comment by cdondrup** [comment]
I think I know the problem, I'll fix it.

**Comment by yianni** [comment]
Isn't this closed by PR #104?

**Comment by cdondrup** [comment]
Should be, yes.
